version: 2.1
defaults: &defaults
  working_directory: /go/src/github.com/aedifex/circleci-golang-demo
  docker:
    - image: golang:1.8

workflows:
  test-build-deploy:
    jobs:
      - build

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run: make build-local
      - run:
          command: ./app
          background: true
      - run: curl localhost:8000/version

  # TODO - cross compile and build ARM exec
  build_arm:
    <<: *defaults
    steps:
      - checkout
      # - run: test arm
