version: 2.1
defaults: &defaults
  working_directory: /go/src/github.com/aedifex/circleci-golang-demo
  docker:
    - image: golang:1.8

workflows:
  test-build-deploy:
    jobs:
      - build-alpine-binary

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: go get
      - run: make build-local
      - run:
          command: ./app
          background: true
      # TODO - turn this into script
      - run: curl localhost:8080/version

  build-alpine-binary:
    <<: *defaults
    steps:
      - checkout
      - run: go get
      - run: make build-linux
      - run:
          command: ./linux-app
          background: true
      # TODO - turn this into script
      - run: curl localhost:8080/version

  # TODO - cross compile and build ARM exec
  # build_arm:
  #   <<: *defaults
  #   steps:
  #     - checkout
      # - run: test arm
